# SQLite version 3.x
 gem install pg
#
#   Ensure the SQLite 3 gem is defined in your Gemfile

development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  password: 
